on:
  push:
    branches:
      - main

jobs:
  update_con_nf_branch_and_build:
    runs-on: ubuntu-latest
    name: Build project
    steps:
      - name: checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install elan
        run: curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain leanprover/lean4:nightly-2023-08-15

      - name: get cache
        run: ~/.elan/bin/lake exe cache get

      - name: build project
        run: ~/.elan/bin/lake -Kenv=dev build ConNF

      - name: build documentation
        run: ~/.elan/bin/lake -Kenv=dev build ConNF:docs

      - name: copy documentation
        run: cp -R build/docs docs/

      - name: remove .gitignore for gh-pages
        run: rm docs/.gitignore

      - name: bundler deps
        uses: ruby/setup-ruby@v1
        with:
          working-directory: docs
          ruby-version: "3.0" # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: bundle website
        working-directory: docs
        run: JEKYLL_ENV=production bundle exec jekyll build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          SINGLE_COMMIT: true
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/_site
