on:
  push:
    branches:
      - main

jobs:
  update_con_nf_branch_and_build:
    runs-on: ubuntu-latest
    name: Update con-nf branch and build project
    steps:
      - name: checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: update branch
        if: github.ref == 'refs/heads/main'
        uses: leanprover-contrib/update-versions-action@master

      - name: install python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: load cache
        uses: actions/cache@v2
        id: cache-id
        with:
          path: ${{ runner.temp }}/cache-directory
          key: ${{ runner.os }}-cache-key-v1.0

      - name: cache new files
        uses: airvzxf/cache-anything-new-action@v1.0.1
        with:
          script: 'install.sh'
          is_cached: ${{ steps.cache-id.outputs.cache-hit }}
          cache: ${{ runner.temp }}/cache-directory
          snapshot: '/'
          exclude: '/boot /data /dev /mnt /proc /run /sys'

      - name: get mathlib cache
        run: leanproject get-mathlib-cache

      - name: build project
        run: lean --make src

      - name: build blueprint
        run: |
          rm docs/.gitignore
          inv all html

      - name: bundler deps
        uses: ruby/setup-ruby@v1
        with:
          working-directory: docs
          ruby-version: "3.0" # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: bundle website
        working-directory: docs
        run: JEKYLL_ENV=production bundle exec jekyll build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          SINGLE_COMMIT: true
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/_site
